### PR TITLE
Usability enhancements

### PR DESCRIPTION
**Pull request by dmitry-cherkas**
Hi @koenbollen , thanks for creating this great tool. We are looking to use it to enable engineers parsing the structured logs and I've introduced few additional parameters to support our use-cases:
* `--exclude-fields` - our logs contain some metadata json keys, which are used by our Log system to properly parse the structured message, but those are not intended for the engineers. Introducing an `exclude` option removes the unwanted metadata from the parsed message.
* `--max-field-length` - we are exposing arbitrary variable values through dedicated json keys (MDC, etc), which are of interest to the engineer. With an option to configure/disable the max field length limit we make sure the important data is not accidentally omitted from the tool output

Above modifications are backward-compatible, in a sense that they should not alter the tool's behavior for any of the existing parameters, but I've also introduced one breaking change which I find reasonable:
* in our use-case the message can be empty, as long as the log entry is a valid JSON, so I removed a check that considers an `Entry.Message == ""` as unparsable entry. I'm happy to discuss alternative approaches to solve this.

Please consider incorporating this contribution and I'll be happy to get you feedback on what could be improved in this PR!

### CODE REVIEW

**Comment by koenbollen** [comment]
Hey @dmitry-cherkas,
Thank you for you contribution, it's really appreciated. The PR and changes are very clean.

The two new commandline parameters are no-brainers to add. 👍🏻 

As for the changed behaviour on empty messages; Seeing that this behaviour is currently not documented I think it's fine to change it. We might want to add it to the documentation though.
And let's wait a day or two before merging so watchers can weigh in.

You'll also notice that the cram tests is failing, this project tests it's documentation and examples in the Markdown files to ensure they are up to date.
Could you please update the documentation to reflect the new behaviour?

**Comment by dmitry-cherkas** [comment]
@koenbollen , thanks for your feedback. I've updated the existing tests and added a few to cover the new configuration options/behavior.

**Comment by koenbollen** [comment]
Cool! One last nitpick, and then we are good to go.
Could you add a newline at the end of the _.gitignore_ and _unstructured_app_ files? That will make Linux users very happy. :)

I will probably have some time over the weekend to make a release (I have to remind myself on howto update my brew). I'll leave open this PR until then, so others have more change/time to comment.

**Review by koenbollen — APPROVED** [review]

**Comment by koenbollen** [comment]
Hey @dmitry-cherkas,

Merged and released.
Also updated the Homebrew formula (https://github.com/koenbollen/homebrew-public/commit/83536ee5a72887ff17e02f0c8cb2e1c058c700d4).

Thanks again! 🎉

**Pull request merged**
